### User Login
POST http://localhost:8000/api/auth/user/login
Content-Type: application/json

{
    "email": "anupam@xeotec.in",
    "password": "aksinghweb"
}

### Logout
POST http://localhost:8000/api/auth/user/logout