### create a permission
POST http://localhost:8000/api/permission/create
Content-Type: application/json
Authorization: Bearer 

{
    "name": "company:role:create",
    "module": "company",
    "resource": "role",
    "action": "create",
    "description": "Permission to create a role"
}

### get all permissions
GET http://localhost:8000/api/permission