POST http://localhost:8000/api/users/superadmin/create
Content-Type: application/json

{
    "email": "admin@xeotec.in",
    "password": "Xeotec@2018#",
    "name": "CRM Administrator",
    "role": "superadmin"
}

### Login as Super Admin
POST http://localhost:8000/api/auth/superadmin/login
Content-Type: application/json

{
    "email": "shamimimran35@gmail.com",
    "password": "Xeotec@2018#"
}

### Verify OTP for Super Admin Login
POST http://localhost:8000/api/auth/superadmin/login/verify-otp
Content-Type: application/json

{
    "otp": "776181",
    "email": "shamimimran35@gmail.com"
}
